#!/bin/bash

declare pw=$("pwd")
declare project=""

if [[ $pw =~ (.*\/)(.*) ]]; then
    project=${BASH_REMATCH[2]}
fi

declare src="$pw/src/$project"
declare bin="$pw/bin"

source ./watch_files

function check_dirs_files() {
    local -n ari=$1

    for page in "${ari[@]}"
    do
        IFS=";" read -r -a arr <<< "${page}"

        declare fde="${arr[1]}"
        declare dirna="$(dirname "${fde}")"

        if [ ! -e $dirna ]; then
            echo "[Check dirs files mk] $dirna"
            mkdir -p $dirna
        fi
    done
}

function copira() {
    local -n acp=$1

    declare some=""

    for page in "${acp[@]}"
    do
        IFS=";" read -r -a arr <<< "${page}"

        declare fos="${arr[0]}"
        declare fot="${arr[1]}"

        declare out=$(cp -uv "$fos" "$fot")

        if [[ ! -z $out ]]; then
            declare bn=$(basename "$fos")

            if [[ ! -z $some ]]; then
                some="${some}"$'\n'
            fi

            some="${some}${bn}"
        fi
    done

    if [[ ! -z $some ]]; then
        echo "$some"
    fi
}

echo -en "\033]0;$TTL\a"

clear

check_dirs_files W_FILES

while true;
do
    copira W_FILES
    sleep 1
done

exit 0
