#!/bin/bash

TTL="wsloca"

C_FOLDERS=(
    "$src/static/images;$bin/static/images"
)

W_FILES=(
# json
    "$src/config.json;$bin/config.json"
# html
    "$src/templates/lays/layout.html;$bin/templates/lays/layout.html"
    "$src/templates/stru/dix.html;$bin/templates/stru/dix.html"
# css
    "$src/static/css/inc/reset.css;$bin/static/css/inc/reset.css"
    "$src/static/css/inc/style.css;$bin/static/css/inc/style.css"
    "$src/static/css/elems/deb.css;$bin/static/css/elems/deb.css"
)
